### ISSUE TITLE
Provide deployment examples

### ISSUE THREAD

**Issue by H4CK3R-01** [markusressel/keel-telegram-bot#117]
**Is your feature request related to a problem? Please describe.**
I'm not able to receive notifications from keel.
I've set up keel through helm and the bot with a separate deployment.
The bot uses a service and an ingress to be available on a subdomain of my domain.
In keel's config I've set 
```
webhook:
  enabled: true
  endpoint: https://keel-telegram.<DOMAIN>
```
In keel's dashboard I can see some approvals but I do not receive them in telegram.

In keel's logs I saw
```
time="2023-03-23T07:35:21Z" level=error msg="could not send notification via notifier" error="got status 403, expected 200/201" notification name="preparing to update resource" sender name=webhook
time="2023-03-23T07:35:21Z" level=info msg="waiting before retrying to send notification" attempts=8 duration=1m4s max attempts=10 notification name="preparing to update resource" sender name=webhook
```
But I don't know what's the exact problem.

**Describe the solution you'd like**
Provide an example deployment and the right settings in keel's config

**Describe alternatives you've considered**

**Additional context**

**Comment by markusressel** [comment]
Hey @H4CK3R-01 :heart: 

I am not sure what is missing from the current `README` for a deployment, it should already contain everything necessary :thinking: 

To me the error you get from keel looks like it is not allowed to access your `https://keel-telegram.<DOMAIN>` target, probably because of a configuration issue of your deployment environment. If you shell into the keel container, can you f.ex. `curl` to the desired target?

**Comment by H4CK3R-01** [comment]
Hi, 
Thank you for the quick response.
I've got it working now. I used the internal address. I think it was an issue of my service or ingress.
