### ISSUE TITLE
Main variable node contains hypen, it should be underscore

### ISSUE THREAD

**Issue by zaggash** [markusressel/keel-telegram-bot#29]
**Describe the bug**
The hyphen in a variable name is not a POSIX  standard

**To Reproduce**
export KEEL-TELEGRAM-BOT_KEEL_PASSWORD="mypassword"

**Expected behavior**
The variable should be created

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by markusressel** [comment]
Thx. Yeah I never really liked that anyway.

Since you are talking about the ENV variables I think this should be implemented in the config library [container-app-conf](https://github.com/markusressel/container-app-conf) (I will create an issue there). Since I do like it to be able to use the hyphen variant in the yaml config, allowing both the hyphen and underscore variant in the ENV source should fix this right?

**Comment by zaggash** [comment]
Yeah, I think a conversion from hyphen to underscore in the config library is the way to go ;)
Thanks for taking care of it ;)

However, it will be a breaking change on this app tho for those like me who uses the current implementation.

**Comment by markusressel** [comment]
Should be fixed with the new release, report back if it isn't.
